version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:  
    build: ./backend
    container_name: New
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend/web_tech
    container_name: New1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:
